version: '3'

services:
  app:
    image: node:lts # バージョン指定も可能 ex. node:12.16.1
    container_name: node_exersise
    tty: true
    # この下の共有フォルダ構成とこのファイル外のフォルダ構成を一致させておくこと
    volumes:
      - ../src:/src
    working_dir: "/src"